# Site settings
title: ''
email: contact@routedlogic.net
url: https://routedlogic.net
description: ''

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Colin Stubbs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/routedlogic
  - title: bitbucket
    url: http://bitbucket.org/routedlogic
  - title: github
    url: https://github.com/routedlogic

# Build settings
markdown: kramdown
permalink: pretty
